name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run iOS tests
      run: xcodebuild test -destination 'name=iPhone 11' -scheme 'NSPersist-Package'
    - name: Run tvOS tests
      run: xcodebuild test -destination 'OS=13.3,name=Apple TV 4K' -scheme 'NSPersist-Package'
    - name: Run macOS tests
      run: xcodebuild test - destination 'macOS' -scheme 'NSPersist-Package'
